[theme]
primaryColor = "#F63366"          # Color for active elements (sliders, etc.)
backgroundColor = "#FFFFFF"       # Main background color
secondaryBackgroundColor = "#F0F2F6" # Sidebar and widget background
textColor = "#262730"             # Main text color


[server]
enableCORS = false
port = 8501
maxUploadSize = 200

[browser]
gatherUsageStats = false          # Disable telemetry
serverAddress = "localhost"
